apiVersion: v1
entries:
  common:
  - annotations:
      category: Infrastructure
      licenses: Apache-2.0
    apiVersion: v2
    appVersion: 2.19.3
    created: "2024-06-06T03:35:02.089359+05:30"
    description: A Library Helm Chart for grouping common logic between bitnami charts.
      This chart is not deployable by itself.
    digest: e009fa62d2b39892337d7bd5be9cdcc0108393f5ba27810c403dc63e8f78c17a
    home: https://bitnami.com
    icon: https://bitnami.com/downloads/logos/bitnami-mark.png
    keywords:
    - common
    - helper
    - template
    - function
    - bitnami
    maintainers:
    - name: Broadcom, Inc. All Rights Reserved.
      url: https://github.com/bitnami/charts
    name: common
    sources:
    - https://github.com/bitnami/charts
    type: library
    urls:
    - https://openvirtualcluster.github.io/virtual-cluster-operator/charts/common-2.19.3.tgz
    version: 2.19.3
  flux:
  - annotations:
      category: Infrastructure
      images: |
        - name: fluxcd-helm-controller
          image: docker.io/bitnami/fluxcd-helm-controller:0.35.0-debian-11-r44
        - name: fluxcd-image-automation-controller
          image: docker.io/bitnami/fluxcd-image-automation-controller:0.31.0-debian-11-r83
        - name: fluxcd-image-reflector-controller
          image: docker.io/bitnami/fluxcd-image-reflector-controller:0.29.1-debian-11-r38
        - name: fluxcd-kustomize-controller
          image: docker.io/bitnami/fluxcd-kustomize-controller:0.35.1-debian-11-r139
        - name: fluxcd-notification-controller
          image: docker.io/bitnami/fluxcd-notification-controller:0.33.0-debian-11-r139
        - name: fluxcd-source-controller
          image: docker.io/bitnami/fluxcd-source-controller:0.36.1-debian-11-r138
        - name: os-shell
          image: docker.io/bitnami/os-shell:11-debian-11-r40
      licenses: Apache-2.0
    apiVersion: v2
    appVersion: 0.36.1
    created: "2024-06-06T03:35:02.094108+05:30"
    dependencies:
    - name: common
      repository: oci://registry-1.docker.io/bitnamicharts
      tags:
      - bitnami-common
      version: 2.x.x
    description: Flux is a tool for keeping Kubernetes clusters in sync with sources
      of configuration
    digest: fdae60193676a059bc2c01057ecbd07eca8a2f9e41cf923978881ffa930030d9
    home: https://bitnami.com
    icon: https://bitnami.com/assets/stacks/fluxcd-kustomize-controller/img/fluxcd-kustomize-controller-stack-220x234.png
    keywords:
    - deployment
    - gitops
    - cd
    - continuous-delivery
    - helm
    - kustomize
    maintainers:
    - name: VMware, Inc.
      url: https://github.com/bitnami/charts
    name: flux
    sources:
    - https://github.com/bitnami/charts/tree/main/bitnami/flux
    urls:
    - https://openvirtualcluster.github.io/virtual-cluster-operator/charts/flux-0.4.1.tgz
    version: 0.4.1
  virtual-cluster-operator:
  - annotations:
      artifacthub.io/category: integration-delivery
      artifacthub.io/prerelease: "false"
    apiVersion: v2
    appVersion: v0.0.3
    created: "2024-06-06T03:35:02.088507+05:30"
    dependencies:
    - name: common
      repository: https://charts.bitnami.com/bitnami
      version: 2.x.x
    - name: flux
      repository: https://charts.bitnami.com/bitnami
      version: 0.x.x
    description: A Helm chart for deploying the Virtual Cluster Operator
    digest: ee84e3e4dc7dc727d914d724c61116d8eede0648b77419b67db29ad5831b5f09
    home: https://openvirtualcluster.dev/
    keywords:
    - ephemeral-environments
    maintainers:
    - email: vibhav@openvirtualcluster.dev
      name: Vibhav Bobade
      url: https://github.com/waveywaves
    name: virtual-cluster-operator
    sources:
    - https://github.com/OpenVirtualCluster/virtual-cluster-operator
    type: application
    urls:
    - https://openvirtualcluster.github.io/virtual-cluster-operator/virtual-cluster-operator-0.0.3.tgz
    version: 0.0.3
generated: "2024-06-06T03:35:02.079556+05:30"
