image:
  tag: v0.0.3
# `flux` dependency values
flux:
  helmController:
    enabled: true
    metrics:
      enabled: false
    args:
      - --watch-all-namespaces
      - --log-level=info
      - --metrics-addr=:8080
      - --health-addr=:9440
      - --log-encoding=json
      - --enable-leader-election
      - --concurrent=20
  sourceController:
    enabled: true
    metrics:
      enabled: false
  kustomizeController:
    enabled: false
  notificationController:
    enabled: false
  imageAutomationController:
    enabled: false
  imageReflectorController:
    enabled: false