apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: openvirtualcluster
    app.kubernetes.io/instance: leader-election-rolebinding
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rolebinding
    app.kubernetes.io/part-of: openvirtualcluster
  name: '{{ include "common.names.fullname" . }}-leader-election-rolebinding'
  namespace: '{{ .Release.Namespace }}'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: openvirtualcluster-leader-election-role
subjects:
  - kind: ServiceAccount
    name: '{{ include "common.names.fullname" . }}-controller-manager'
    namespace: '{{ .Release.Namespace }}'
