apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: openvirtualcluster
    app.kubernetes.io/instance: manager-rolebinding
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: clusterrolebinding
    app.kubernetes.io/part-of: openvirtualcluster
  name: '{{ include "common.names.fullname" . }}-manager-rolebinding'
  namespace: '{{ .Release.Namespace }}'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "common.names.fullname" . }}-manager-role'
subjects:
  - kind: ServiceAccount
    name: '{{ include "common.names.fullname" . }}-controller-manager'
    namespace: '{{ .Release.Namespace }}'
