# permissions for end users to view vclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: virtual-cluster-operator
    app.kubernetes.io/managed-by: kustomize
  name: vcluster-viewer-role
rules:
- apiGroups:
  - vclusters.openvirtualcluster.dev
  resources:
  - vclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - vclusters.openvirtualcluster.dev
  resources:
  - vclusters/status
  verbs:
  - get
