apiVersion: vclusters.openvirtualcluster.dev/v1alpha1
kind: Vcluster
metadata:
  labels:
    app.kubernetes.io/name: virtual-cluster-operator
    app.kubernetes.io/managed-by: kustomize
  name: vcluster-sample
spec:
  # TODO(user): Add fields here
