name: GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.7.1

      - name: Package Helm Chart
        run: |
          helm dep update ./chart
          helm package ./chart -d ./chart

      - name: Build Helm Index
        run: helm repo index ./chart --url https://charts.openvirtualcluster.dev/virtual-cluster-operator

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.HELM_GITHUB_PAT }}
          publish_dir: ./chart
          publish_branch: gh-pages
